name: Maven build and deploy to Azure

on:
  push:
    branches: [ "main" ]

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 68655a8a-50c6-464a-a5ff-6b8c2d342842

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to staging with artifact
      uses: azure/spring-apps-deploy@v1
      with:
        azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
        action: deploy
        service-name: alerant-meetup
        app-name: frontend
        use-staging-deployment: true
        package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar
